# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Dev\py\gui-saver\gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 591))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.VL_main = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.VL_main.setContentsMargins(0, 0, 0, 0)
        self.VL_main.setObjectName("VL_main")
        self.HL_game_dir = QtWidgets.QHBoxLayout()
        self.HL_game_dir.setObjectName("HL_game_dir")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.HL_game_dir.addWidget(self.label)
        self.LE_choose_dir = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.LE_choose_dir.setFont(font)
        self.LE_choose_dir.setFrame(True)
        self.LE_choose_dir.setDragEnabled(True)
        self.LE_choose_dir.setPlaceholderText("")
        self.LE_choose_dir.setClearButtonEnabled(True)
        self.LE_choose_dir.setObjectName("LE_choose_dir")
        self.HL_game_dir.addWidget(self.LE_choose_dir)
        self.B_choose_dir = QtWidgets.QToolButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.B_choose_dir.setFont(font)
        self.B_choose_dir.setObjectName("B_choose_dir")
        self.HL_game_dir.addWidget(self.B_choose_dir)
        self.B_choose_dir_confirm = QtWidgets.QPushButton(self.layoutWidget)
        self.B_choose_dir_confirm.setObjectName("B_choose_dir_confirm")
        self.HL_game_dir.addWidget(self.B_choose_dir_confirm)
        self.VL_main.addLayout(self.HL_game_dir)
        self.save_name_HL = QtWidgets.QHBoxLayout()
        self.save_name_HL.setObjectName("save_name_HL")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.save_name_HL.addWidget(self.label_4)
        self.S_save_name = QtWidgets.QComboBox(self.layoutWidget)
        self.S_save_name.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S_save_name.sizePolicy().hasHeightForWidth())
        self.S_save_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.S_save_name.setFont(font)
        self.S_save_name.setObjectName("S_save_name")
        self.save_name_HL.addWidget(self.S_save_name)
        self.VL_main.addLayout(self.save_name_HL)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.B_backup = QtWidgets.QPushButton(self.layoutWidget)
        self.B_backup.setEnabled(False)
        self.B_backup.setCheckable(False)
        self.B_backup.setFlat(False)
        self.B_backup.setObjectName("B_backup")
        self.horizontalLayout_2.addWidget(self.B_backup)
        self.LE_comment = QtWidgets.QLineEdit(self.layoutWidget)
        self.LE_comment.setMouseTracking(False)
        self.LE_comment.setMaxLength(25)
        self.LE_comment.setClearButtonEnabled(True)
        self.LE_comment.setObjectName("LE_comment")
        self.horizontalLayout_2.addWidget(self.LE_comment)
        self.CB_important = QtWidgets.QCheckBox(self.layoutWidget)
        self.CB_important.setObjectName("CB_important")
        self.horizontalLayout_2.addWidget(self.CB_important)
        self.VL_main.addLayout(self.horizontalLayout_2)
        self.HL_auto_backup = QtWidgets.QHBoxLayout()
        self.HL_auto_backup.setObjectName("HL_auto_backup")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.HL_auto_backup.addWidget(self.label_5)
        self.SB_auto_time = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.SB_auto_time.setFont(font)
        self.SB_auto_time.setObjectName("SB_auto_time")
        self.HL_auto_backup.addWidget(self.SB_auto_time)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.HL_auto_backup.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HL_auto_backup.addItem(spacerItem)
        self.B_auto_control = QtWidgets.QPushButton(self.layoutWidget)
        self.B_auto_control.setEnabled(False)
        self.B_auto_control.setObjectName("B_auto_control")
        self.HL_auto_backup.addWidget(self.B_auto_control)
        self.VL_main.addLayout(self.HL_auto_backup)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.VL_main.addWidget(self.label_2)
        self.backup_table = QtWidgets.QTableWidget(self.layoutWidget)
        self.backup_table.setShowGrid(True)
        self.backup_table.setRowCount(0)
        self.backup_table.setColumnCount(4)
        self.backup_table.setObjectName("backup_table")
        self.backup_table.horizontalHeader().setVisible(True)
        self.backup_table.horizontalHeader().setCascadingSectionResizes(False)
        self.backup_table.horizontalHeader().setHighlightSections(False)
        self.backup_table.horizontalHeader().setMinimumSectionSize(0)
        self.backup_table.horizontalHeader().setSortIndicatorShown(False)
        self.backup_table.horizontalHeader().setStretchLastSection(True)
        self.backup_table.verticalHeader().setCascadingSectionResizes(False)
        self.backup_table.verticalHeader().setDefaultSectionSize(25)
        self.backup_table.verticalHeader().setHighlightSections(False)
        self.backup_table.verticalHeader().setMinimumSectionSize(0)
        self.VL_main.addWidget(self.backup_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.B_reload = QtWidgets.QPushButton(self.layoutWidget)
        self.B_reload.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.B_reload.setFont(font)
        self.B_reload.setObjectName("B_reload")
        self.horizontalLayout.addWidget(self.B_reload)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.B_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.B_delete.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.B_delete.setFont(font)
        self.B_delete.setObjectName("B_delete")
        self.horizontalLayout.addWidget(self.B_delete)
        self.B_delete_f = QtWidgets.QPushButton(self.layoutWidget)
        self.B_delete_f.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.B_delete_f.setFont(font)
        self.B_delete_f.setObjectName("B_delete_f")
        self.horizontalLayout.addWidget(self.B_delete_f)
        self.VL_main.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Saver"))
        self.label.setText(_translate("MainWindow", "Game dir : "))
        self.B_choose_dir.setText(_translate("MainWindow", "..."))
        self.B_choose_dir_confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_4.setText(_translate("MainWindow", "Save name: "))
        self.B_backup.setText(_translate("MainWindow", "Backup"))
        self.LE_comment.setPlaceholderText(_translate("MainWindow", "comment"))
        self.CB_important.setText(_translate("MainWindow", "Mark as important"))
        self.label_5.setText(_translate("MainWindow", "Auto backup per"))
        self.label_3.setText(_translate("MainWindow", "minutes"))
        self.B_auto_control.setText(_translate("MainWindow", "Start/Stop"))
        self.label_2.setText(_translate("MainWindow", "Backup list:"))
        self.B_reload.setText(_translate("MainWindow", "Reload"))
        self.B_delete.setText(_translate("MainWindow", "Delete"))
        self.B_delete_f.setText(_translate("MainWindow", "Delete -f"))

